#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

#1. Load all modules 
module load python2 samtools/0.1.19 bowtie2 boost tophat

#2. Run tophat to align the two FASTQ files against mm9 reference
tophat -r 200 -G /projectnb/bf528/project_2/reference/annot/mm9.gtf --segment-length=20 --segment-mismatches=1 --no-novel-juncs -o P0_1_tophat -p 16 /project/bf528/project_2/reference/mm9 /projectnb/bf528/users/glass_bottom_boat/project_2/data_curator/P0_1_1.fastq /projectnb/bf528/users/glass_bottom_boat/project_2/data_curator/P0_1_2.fastq


echo "Job finished: $(date +%F)"
